# NumPy tutorial

[Numerical Python](https://numpy.org) is one of the most fundamental tools in each data miner's toolbox. It is impossible to do serious data pre-processing and transformation without the understanding of `NumPy` and its most commonly used methods. The goal of this tutorial is to familiarize students with this awesome library.

## Introduction

Python is among the least efficient languages out there. Data mining is a field of study, which requires a lot of processing power. Why would we ever want to use python in order to do the data mining? The answer is really simple - we do not. We use python only as an interface to packages, which contain very efficient and optimized programs, such as numpy, scipy, sklearn, tensorflow, pytorch, keras... The list is long. Python is very flexible and simple. We just like its syntax, ability to combine it with programs written in other languages, not necessairly its efficency. In the previous tutorial we have already seen some numpy stuctures. When we imported the toy data sets, the data was stored in something called ndarray. In fact 99% of `NumPy` is about this very data structure and operations on this structure. `NumPy` stores everything in multidimensional arrays and vectorizes all operations on these arrays. 

Contrary to Python lists, the NumPy arrays represent tensors (e.g. 1st rank tensor - a vector, 2nd rank tensor - a matrix; do not confuse this with Tensorflow tensor data structure, tensors in a mathematical sense). Python list is just a list of things, specifically it could be a list of lists, there is no additional limitation to that. A tensor has some limitations:
- every element must be of the same type and size
- if an array has arrays, they must match as well

After all this:

\begin{matrix} 1 & 2 & 3 \\ 4 & 5 & 6 & 8 \\ 7 & 8 &  \end{matrix}

is not a matrix.

While this:



In [1]:
lst = [[1,2,3],[4,5,6,8],[7,8]]

is a list.

For a motivating example, let's compare the speed of computing an average of 10 mln of random numbers stored in a list vs an array

First, we are going to generate a list of 10 mln random numbers. We will use a function from the numpy package named randint. As you might suspect the function can be used to generate a random integer. In fact this function is flexible enough to create a tensor of any shape with random integers.

In [2]:
import numpy as np
from numpy.random import randint

randoms = randint(low=0, high=1000, size=(1000,1000))
randoms = randint(low=0, high=1000, size=(100,100,100))
randoms = randint(low=0, high=1000, size=(10,10000))
randoms = randint(low=0, high=1000, size=(10000000))
lst = list(randoms)

I hope you're not surprised the size is not just a single number. n-th rank tensor requires n numbers to describe its shape. A vector has just its length. A matrix has a number of columns and a number of rows. A cuboid has three dimensions, and so on. So, in the second to last line we generated a vector of 10 mln random numbers. In the last line we converted it to a list. We can get the length of this list with a built-in len function.

In [3]:
len(lst)

10000000

We expect the len function to return an integer. So it does. If we try to check the length of a numpy array we are going to get only the size of the first dimension. If we want to get a full description of the tensor shape, we can use the `shape` attribute.

In [4]:
sample = np.zeros((1000,1000,1000))

print(len(sample))
print(sample.shape)

1000
(1000, 1000, 1000)


Let's start the calculation of an average - we will use the cell magic here to compare the solutions.

In [6]:
%%time

# old-school iteration
summ = 0
for i in range(len(lst)):
    summ += lst[i]
    
print(f'Average = {summ/len(lst)}')

Average = 499.4664618
CPU times: user 2.11 s, sys: 31 µs, total: 2.11 s
Wall time: 2.13 s


In [7]:
%%time

# using built-ins sum() and len()
print(f'Average = {sum(lst)/len(lst)}')

Average = 499.4664618
CPU times: user 382 ms, sys: 3.07 ms, total: 385 ms
Wall time: 388 ms


In [8]:
%%time

# using NumPy
print(f'Average = {np.mean(randoms)}')

Average = 499.4664618
CPU times: user 25.4 ms, sys: 0 ns, total: 25.4 ms
Wall time: 24.6 ms


Let's see how to create an array and what happens when we start messing with the types and sizes of objects.

In the previous examples we already saw how to create an array of random numbers (and an array, which consists of zeros).
We can also create a numpy array with a python list, like this:

In [9]:
a = np.array([1, 2, 3, 4, 5])



we have also seen how to get the exact shape of an array. In fact there are more descriptors for an array.

In [10]:
print(f"""
Shape (sizes of dimensions): {a.shape}
Number of dimensions: {a.ndim}
Length (number of elements): {len(a)}
Size (number of nested elements): {a.size}
Type : {type(a)}
Data type (type of array elements): {a.dtype}
""")


Shape (sizes of dimensions): (5,)
Number of dimensions: 1
Length (number of elements): 5
Size (number of nested elements): 5
Type : <class 'numpy.ndarray'>
Data type (type of array elements): int64



Now let's see how the same descriptors can be applied to a two- and three -dimensional array

In [11]:
a = np.array([
    [1, 2, 3, 4, 5],
    [1, 4, 9, 16, 25]
])

print(f"""
Shape (sizes of dimensions): {a.shape}
Number of dimensions: {a.ndim}
Length (number of elements): {len(a)}
Size (number of nested elements): {a.size}
Type : {type(a)}
Data type (type of array elements): {a.dtype}
""")


Shape (sizes of dimensions): (2, 5)
Number of dimensions: 2
Length (number of elements): 2
Size (number of nested elements): 10
Type : <class 'numpy.ndarray'>
Data type (type of array elements): int64



In [12]:
a = np.array([
    [
    [1, 2, 3, 4, 5],
    [1, 1, 2, 3, 5]
    ],
    [
    [1, 2, 3, 4, 5],
    [1, 4, 9, 16, 25]
    ]
])

print(f"""
Shape (sizes of dimensions): {a.shape}
Number of dimensions: {a.ndim}
Length (number of elements): {len(a)}
Size (number of nested elements): {a.size}
Type : {type(a)}
Data type (type of array elements): {a.dtype}
""")


Shape (sizes of dimensions): (2, 2, 5)
Number of dimensions: 3
Length (number of elements): 2
Size (number of nested elements): 20
Type : <class 'numpy.ndarray'>
Data type (type of array elements): int64



Array elements should be of the same type. Let's see what happens if we mix two or more types.

In [13]:
a = np.array([1, 2, 'mary', 'had', 2.5, 'lambs'])
a

array(['1', '2', 'mary', 'had', '2.5', 'lambs'], dtype='<U32')

In [14]:
a.dtype

dtype('<U32')

We can also try to modify the length of array's elements

In [15]:
a = np.array(['mary', 'had', 'a', 'little', 'lamb'])
a.dtype

dtype('<U6')

In [18]:
a[4] = 'and very very very very long snake'
a

ValueError: invalid literal for int() with base 10: 'and very very very very long snake'

After an array has been created, it can be reshaped to whatever shape one desires. A special function is provided for transposing an array (changing rows into columns and vice versa)

In [19]:
a = np.array(list(range(12)))

a.shape = (3,4)
a

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [20]:
a = a.reshape(6, 2)
a

array([[ 0,  1],
       [ 2,  3],
       [ 4,  5],
       [ 6,  7],
       [ 8,  9],
       [10, 11]])

In [21]:
a.T

array([[ 0,  2,  4,  6,  8, 10],
       [ 1,  3,  5,  7,  9, 11]])

## Creating arrays

The easiest way to create a 1-d array is to use a list. If you want a 2-d array, you use a list of lists. 3-d arrays are created using a list of lists of lists. You get the gist.

In [22]:
a_1d = np.array([1, 2, 3, 4])

a_2d = np.array([
    [1, 2, 3, 4],
    [1, 4, 9, 16],
    [1, 8, 27, 64]
])

a_3d = np.array([
    [
        [0, 0],
        [0, 1],
    ],
    [
        [1, 0],
        [1, 1],
    ],
])

There are utility functions in the `np` module for creating popular types of arrays:
- an array filled with zeros
- an array filled with ones
- an array filled with any value
- an array of consecutive (or stepped) values
- an array filled with random values
- a diagonal array

In [23]:
np.zeros(shape=(3,3))

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [24]:
np.zeros(shape=(3,5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [25]:
np.ones(10)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [26]:
np.ones(10, dtype=np.int32)

array([1, 1, 1, 1, 1, 1, 1, 1, 1, 1], dtype=int32)

In [27]:
np.full(shape=(4,4), fill_value='empty')

array([['empty', 'empty', 'empty', 'empty'],
       ['empty', 'empty', 'empty', 'empty'],
       ['empty', 'empty', 'empty', 'empty'],
       ['empty', 'empty', 'empty', 'empty']], dtype='<U5')

In [28]:
??np.arange

Docstring:
arange([start,] stop[, step,], dtype=None, *, like=None)

Return evenly spaced values within a given interval.

``arange`` can be called with a varying number of positional arguments:

* ``arange(stop)``: Values are generated within the half-open interval
  ``[0, stop)`` (in other words, the interval including `start` but
  excluding `stop`).
* ``arange(start, stop)``: Values are generated within the half-open
  interval ``[start, stop)``.
* ``arange(start, stop, step)`` Values are generated within the half-open
  interval ``[start, stop)``, with spacing between values given by
  ``step``.

For integer arguments the function is roughly equivalent to the Python
built-in :py:class:`range`, but returns an ndarray rather than a ``range``
instance.

When using a non-integer step, such as 0.1, it is often better to use
`numpy.linspace`.

See the Warning sections below for more information.

Parameters
----------
start : integer or real, optional
    Start of interval.  The interva

In [29]:
np.arange(-2, 2, 0.5)

array([-2. , -1.5, -1. , -0.5,  0. ,  0.5,  1. ,  1.5])

In [30]:
np.random.randn(3, 3, 2)

array([[[ 1.13072733, -0.7630362 ],
        [-1.32065521,  0.10414325],
        [-0.18526901,  0.79518184]],

       [[-0.77667374, -1.30318229],
        [ 1.30504639, -0.21759502],
        [ 0.19032885,  0.34217152]],

       [[-0.84359886,  1.00195619],
        [ 0.03090637, -0.21850373],
        [-2.13887734, -0.38763719]]])

In [31]:
np.random.randint(low=1, high=7, size=10)

array([5, 2, 4, 6, 6, 1, 6, 2, 4, 2])

In [32]:
np.eye(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [33]:
np.eye(5, 8)

array([[1., 0., 0., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0., 0.]])

## Indexing arrays

Arrays in `NumPy` are 0-indexed. Indexing of 1-d arrays is very easy, just follow the pattern of *start*:*end*:*step*

In [34]:
a = np.arange(0, 10)

print(f"""{a}

First element: {a[0]}
First three elements: {a[0:3]}
Last element: {a[len(a)-1]} and {a[-1]}
Even elements: {a[::2]}
""")

[0 1 2 3 4 5 6 7 8 9]

First element: 0
First three elements: [0 1 2]
Last element: 9 and 9
Even elements: [0 2 4 6 8]



Indexing of n-dim arrays is a bit more tricky. Keep in mind that axis 0 refers to rows and axis 1 refers to columns. For high dimensional arrays try to build the following intuition:
- 1-d: a row of values
- 2-d: a matrix (rows and columns) of values
- 3-d: a row of arrays
- 4-d: a matrix of arrays
- and so on...

In [35]:
a = np.array([
    [1, 2, 3, 4],
    [10, 20, 30, 40],
    [100, 200, 300, 400],
])

print(f"""{a}

Element at second row, third column: {a[1,2]}
Entire first row: {a[0]}
Entire first row as 2-d array: {a[0, None]}
First and second rows, last column: {a[:2,-1]}
""")

[[  1   2   3   4]
 [ 10  20  30  40]
 [100 200 300 400]]

Element at second row, third column: 30
Entire first row: [1 2 3 4]
Entire first row as 2-d array: [[1 2 3 4]]
First and second rows, last column: [ 4 40]



The same goes with all n-dim arrays. For instance, let's extract first matrix, all rows, first column. You can also use indexing to assign multiple values to array cell at once.

In [36]:
a_3d

array([[[0, 0],
        [0, 1]],

       [[1, 0],
        [1, 1]]])

In [37]:
a_3d[0, :,0]

array([0, 0])

In [38]:
a_3d[1, :, 1] = -1

print(a_3d)

[[[ 0  0]
  [ 0  1]]

 [[ 1 -1]
  [ 1 -1]]]


## Basic operations on arrays

All array operations are vectorized, so they tend to be very quick. By default, `NumPy` performs element-wise array operations. If you want to correctly multiply arrays, use `@` operator as shown below.

In [39]:
a = np.arange(0, 12)
b = np.arange(12, 24)

a.shape = b.shape = 3, 4

In [40]:
a

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [41]:
b

array([[12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

In [42]:
a + b

array([[12, 14, 16, 18],
       [20, 22, 24, 26],
       [28, 30, 32, 34]])

In [43]:
b - a

array([[12, 12, 12, 12],
       [12, 12, 12, 12],
       [12, 12, 12, 12]])

In [44]:
a * 10

array([[  0,  10,  20,  30],
       [ 40,  50,  60,  70],
       [ 80,  90, 100, 110]])

In [45]:
a @ b.T

array([[ 86, 110, 134],
       [302, 390, 478],
       [518, 670, 822]])

## Homework

### Calculating sliding averages

Given an array of daily measurements, create a new array with averages computed over each pair of consecutive days. Compare the execution time of various solutions.

In the first solution you should use the for loop comprehension in order to create an array of pairs of measurements. Then, using the numpy average function calculate averages over the list of pairs.

In [48]:
measurements = np.arange(100)
measurements

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
       68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84,
       85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99])

In [47]:
??np.average

Signature:      
np.average(
    a,
    axis=None,
    weights=None,
    returned=False,
    *,
    keepdims=<no value>,
)
Call signature:  np.average(*args, **kwargs)
Type:            _ArrayFunctionDispatcher
String form:     <function average at 0x7fae3047f240>
File:            ~/anaconda3/lib/python3.11/site-packages/numpy/lib/function_base.py
Source:         
@array_function_dispatch(_average_dispatcher)
def average(a, axis=None, weights=None, returned=False, *,
            keepdims=np._NoValue):
    """
    Compute the weighted average along the specified axis.

    Parameters
    ----------
    a : array_like
        Array containing data to be averaged. If `a` is not an array, a
        conversion is attempted.
    axis : None or int or tuple of ints, optional
        Axis or axes along which to average `a`.  The default,
        axis=None, will average over all of the elements of the input array.
        If axis is negative it counts from the last to the first axis.

        ..

In [52]:
%%timeit
pairs = [[measurements[i],measurements[i]] for i in range(len(measurements)-1)]
np.mean(pairs,axis=1)

113 µs ± 27.1 µs per loop (mean ± std. dev. of 7 runs, 1,000 loops each)


In the second solution you are still supposed to create an array of pairs of measurements. This time use the numpy vstack to stack two duplicates of the measurements array. Cut the last day from the first duplicate, cut the first day from the second duplicate. Remember to check the validity of the solution, use transposition if necessary.

In [53]:
??np.vstack

Signature:       np.vstack(tup, *, dtype=None, casting='same_kind')
Call signature:  np.vstack(*args, **kwargs)
Type:            _ArrayFunctionDispatcher
String form:     <function vstack at 0x7fae30558a40>
File:            ~/anaconda3/lib/python3.11/site-packages/numpy/core/shape_base.py
Source:         
@array_function_dispatch(_vhstack_dispatcher)
def vstack(tup, *, dtype=None, casting="same_kind"):
    """
    Stack arrays in sequence vertically (row wise).

    This is equivalent to concatenation along the first axis after 1-D arrays
    of shape `(N,)` have been reshaped to `(1,N)`. Rebuilds arrays divided by
    `vsplit`.

    This function makes most sense for arrays with up to 3 dimensions. For
    instance, for pixel-data with a height (first axis), width (second axis),
    and r/g/b channels (third axis). The functions `concatenate`, `stack` and
    `block` provide more general stacking and concatenation operations.

    ``np.row_stack`` is an alias for `vstack`. They are th

In [54]:
??np.transpose

Signature:       np.transpose(a, axes=None)
Call signature:  np.transpose(*args, **kwargs)
Type:            _ArrayFunctionDispatcher
String form:     <function transpose at 0x7fae305516c0>
File:            ~/anaconda3/lib/python3.11/site-packages/numpy/core/fromnumeric.py
Source:         
@array_function_dispatch(_transpose_dispatcher)
def transpose(a, axes=None):
    """
    Returns an array with axes transposed.

    For a 1-D array, this returns an unchanged view of the original array, as a
    transposed vector is simply the same vector.
    To convert a 1-D array into a 2-D column vector, an additional dimension
    must be added, e.g., ``np.atleast2d(a).T`` achieves this, as does
    ``a[:, np.newaxis]``.
    For a 2-D array, this is the standard matrix transpose.
    For an n-D array, if axes are given, their order indicates how the
    axes are permuted (see Examples). If axes are not provided, then
    ``transpose(a).shape == a.shape[::-1]``.

    Parameters
    ----------
   

In [56]:
a = np.array([[1,2,3],[2,3,4]])
print(a)
print(a.T)

[[1 2 3]
 [2 3 4]]
[[1 2]
 [2 3]
 [3 4]]


In [58]:
%%timeit
np.mean(np.vstack((measurements[1:],measurements[:-1])),axis=0)

23.9 µs ± 1.79 µs per loop (mean ± std. dev. of 7 runs, 10,000 loops each)


In your third solution use the discrete convolution function. This time you calculate the averages with the convolution directly, you don't need to use average function here.

An example of discrete convolution:

given a filter $G=[g_1,g_2,g_3]$ and a vector (1st rank tensor) $V=[v_1,v_2,v_3,v_4,v_5,v_6]$ the convolution of the vector $V$ and a filter $G$ is calculated as follows:

$$V * G = [g_1\cdot v_1+g_2\cdot v_2+g_3\cdot v_3,$$
$$g_1\cdot v_2+g_2\cdot v_3+g_3\cdot v_4,$$
$$g_1\cdot v_3+g_2\cdot v_4+g_3\cdot v_5,$$
$$g_1\cdot v_4+g_2\cdot v_5+g_3\cdot v_6]$$

keep in mind that the filter can be of any size as long as each of its components (of the shape) is equal or lower than its equivalent in the tensor. However, the dimensionality of the filter has to be the same as the dimensionality of the tensor (the filter could be of a lower dimensionality, but then it should be interpreted as if it was of the same dimensionality as the tensor). Notice the similarity between sliding window and the convolution - in both cases you put a "window" or a "filter" on the data and move the window throughout the data. In the example above the window moves like this:

[**_1,2,3_**,4,5,6]

[1,**_2,3,4_**,5,6]

[1,2,**_3,4,5_**,6]

[1,2,3**_,4,5,6_**]


In [61]:
??np.convolve

Signature:       np.convolve(a, v, mode='full')
Call signature:  np.convolve(*args, **kwargs)
Type:            _ArrayFunctionDispatcher
String form:     <function convolve at 0x7fae30559ee0>
File:            ~/anaconda3/lib/python3.11/site-packages/numpy/core/numeric.py
Source:         
@array_function_dispatch(_convolve_dispatcher)
def convolve(a, v, mode='full'):
    """
    Returns the discrete, linear convolution of two one-dimensional sequences.

    The convolution operator is often seen in signal processing, where it
    models the effect of a linear time-invariant system on a signal [1]_.  In
    probability theory, the sum of two independent random variables is
    distributed according to the convolution of their individual
    distributions.

    If `v` is longer than `a`, the arrays are swapped before computation.

    Parameters
    ----------
    a : (N,) array_like
        First one-dimensional input array.
    v : (M,) array_like
        Second one-dimensional input arr

In [67]:
# %%timeit
np.convolve(measurements,np.array([0.5,0.5]),mode="valid")

array([ 0.5,  1.5,  2.5,  3.5,  4.5,  5.5,  6.5,  7.5,  8.5,  9.5, 10.5,
       11.5, 12.5, 13.5, 14.5, 15.5, 16.5, 17.5, 18.5, 19.5, 20.5, 21.5,
       22.5, 23.5, 24.5, 25.5, 26.5, 27.5, 28.5, 29.5, 30.5, 31.5, 32.5,
       33.5, 34.5, 35.5, 36.5, 37.5, 38.5, 39.5, 40.5, 41.5, 42.5, 43.5,
       44.5, 45.5, 46.5, 47.5, 48.5, 49.5, 50.5, 51.5, 52.5, 53.5, 54.5,
       55.5, 56.5, 57.5, 58.5, 59.5, 60.5, 61.5, 62.5, 63.5, 64.5, 65.5,
       66.5, 67.5, 68.5, 69.5, 70.5, 71.5, 72.5, 73.5, 74.5, 75.5, 76.5,
       77.5, 78.5, 79.5, 80.5, 81.5, 82.5, 83.5, 84.5, 85.5, 86.5, 87.5,
       88.5, 89.5, 90.5, 91.5, 92.5, 93.5, 94.5, 95.5, 96.5, 97.5, 98.5])

In this solution use the numpy insert to add a 0 at the beginning of the measurements array (for padding purposes). Then calculate the cumulative sums of the measurements. Finally use the cumulative sum array in order to calculate the averages (it is a combination of picking elements in the correct order and a simple numerical operation). 

hint:

measurements = [1**,2,3,**4,5,6]

cumulative_sums = [0,**1**,3,**6**,10,15,21]

$$c_1 = x_0+x_1$$
$$c_3=x_0+x_1+x_2+x_3$$
$$c_3-c_1 = x_2+x_3$$

measurements = [1,2,**3,4**,5,6]

cumulative_sums = [0,1,**3**,6,**10**,15,21]

$$c_2 = x_0+x_1+x_2$$
$$c_2=x_0+x_1+x_2+x_3+x_4$$
$$c_3-c_1 = x_3+x_4$$



In [62]:
??np.insert

Signature:       np.insert(arr, obj, values, axis=None)
Call signature:  np.insert(*args, **kwargs)
Type:            _ArrayFunctionDispatcher
String form:     <function insert at 0x7fae3049e8e0>
File:            ~/anaconda3/lib/python3.11/site-packages/numpy/lib/function_base.py
Source:         
@array_function_dispatch(_insert_dispatcher)
def insert(arr, obj, values, axis=None):
    """
    Insert values along the given axis before the given indices.

    Parameters
    ----------
    arr : array_like
        Input array.
    obj : int, slice or sequence of ints
        Object that defines the index or indices before which `values` is
        inserted.

        .. versionadded:: 1.8.0

        Support for multiple insertions when `obj` is a single scalar or a
        sequence with one element (similar to calling insert multiple
        times).
    values : array_like
        Values to insert into `arr`. If the type of `values` is different
        from that of `arr`, `values` is conve

In [63]:
??np.cumsum

Signature:       np.cumsum(a, axis=None, dtype=None, out=None)
Call signature:  np.cumsum(*args, **kwargs)
Type:            _ArrayFunctionDispatcher
String form:     <function cumsum at 0x7fae30552fc0>
File:            ~/anaconda3/lib/python3.11/site-packages/numpy/core/fromnumeric.py
Source:         
@array_function_dispatch(_cumsum_dispatcher)
def cumsum(a, axis=None, dtype=None, out=None):
    """
    Return the cumulative sum of the elements along a given axis.

    Parameters
    ----------
    a : array_like
        Input array.
    axis : int, optional
        Axis along which the cumulative sum is computed. The default
        (None) is to compute the cumsum over the flattened array.
    dtype : dtype, optional
        Type of the returned array and of the accumulator in which the
        elements are summed.  If `dtype` is not specified, it defaults
        to the dtype of `a`, unless `a` has an integer dtype with a
        precision less than that of the default platform inte

In [82]:
%%timeit
mes = np.insert(measurements,0,0)
cumulative_sums = np.cumsum(mes)
temp = cumulative_sums[2:]-mes[:-2]
[temp[i]/2 for i in range(len(temp))]

61 µs ± 10.5 µs per loop (mean ± std. dev. of 7 runs, 10,000 loops each)


## Broadcasting

This is by far the most important concept in `NumPy`. Broadcasting is an automatic expansion of arrays so that they match with their operands.

Let's start with the simplest example.

In [7]:
a = np.arange(10)

a + 10

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19])

The same happens for 2-d arrays

In [8]:
a = np.array([
    [1, 2, 3, 4],
    [1, 4, 9, 16],
])

b = np.array([
    [0.1, 0.2, 0.3, 0.4]
])

In [9]:
a

array([[ 1,  2,  3,  4],
       [ 1,  4,  9, 16]])

In [10]:
b

array([[0.1, 0.2, 0.3, 0.4]])

In [11]:
a + b

array([[ 1.1,  2.2,  3.3,  4.4],
       [ 1.1,  4.2,  9.3, 16.4]])

In [12]:
a.shape, b.shape

((2, 4), (1, 4))

The simple rule for broadcasting is the following:

If we want to operate on two arrays `a` and `b`:
- moving backwards from the last dimension of each array, we check if their dimensions are the same or one equals 1
- if all of `a`'s dimensions are compatible with `b`'s dimensions, arrays `a` and `b` are compatible.

In [13]:
np.random.seed(1234)

a = np.random.randint(low = 1, high = 10, size = (3, 4))
a

array([[4, 7, 6, 5],
       [9, 2, 8, 7],
       [9, 1, 6, 1]])

In [14]:
b = np.random.randint(low = 1, high = 10, size = (3, 1))
b

array([[7],
       [3],
       [1]])

In [15]:
a + b

array([[11, 14, 13, 12],
       [12,  5, 11, 10],
       [10,  2,  7,  2]])

In [16]:
np.random.seed(1234)

a = np.random.randint(low = 1, high = 10, size = (3, 1, 4))
a

array([[[4, 7, 6, 5]],

       [[9, 2, 8, 7]],

       [[9, 1, 6, 1]]])

In [17]:
b = np.random.randint(low = 1, high = 10, size = (2, 1))
b

array([[7],
       [3]])

In [18]:
a + b

array([[[11, 14, 13, 12],
        [ 7, 10,  9,  8]],

       [[16,  9, 15, 14],
        [12,  5, 11, 10]],

       [[16,  8, 13,  8],
        [12,  4,  9,  4]]])

Sometimes it is useful to be able to manually modify the shape of the array. This can be done using the `np.newaxis` function (which is simply an alias for the `None` keyword)

In [19]:
a = np.array([1, 2, 3, 5, 7, 11, 13])

In [20]:
a

array([ 1,  2,  3,  5,  7, 11, 13])

In [21]:
a[:, np.newaxis]

array([[ 1],
       [ 2],
       [ 3],
       [ 5],
       [ 7],
       [11],
       [13]])

In [22]:
a[None, :]

array([[ 1,  2,  3,  5,  7, 11, 13]])

This can be very useful if one wants to build an array containing the results of a cross-join operation on two matrices. Suppose we are trying to create $c_{ij} = a_i - b_j$.

In [23]:
b = np.arange(7)
c = a[:, None] - b[None, :]
c

array([[ 1,  0, -1, -2, -3, -4, -5],
       [ 2,  1,  0, -1, -2, -3, -4],
       [ 3,  2,  1,  0, -1, -2, -3],
       [ 5,  4,  3,  2,  1,  0, -1],
       [ 7,  6,  5,  4,  3,  2,  1],
       [11, 10,  9,  8,  7,  6,  5],
       [13, 12, 11, 10,  9,  8,  7]])

## Homework

### Battleships

Given a 10x10 playing field with hidden battleships and a list of shooting targets, compute the number of hits. You are only allowed to use the following functions:

 - ndarray.take
 - ndarray.T
 - ndarray.shape



In [2]:
sea = np.random.randint(low=0, high=2, size=(10,10))

sea


array([[0, 0, 0, 0, 0, 0, 1, 0, 0, 1],
       [1, 0, 1, 1, 1, 1, 1, 0, 1, 0],
       [1, 1, 0, 1, 0, 0, 1, 0, 0, 1],
       [1, 0, 0, 1, 1, 0, 1, 0, 1, 1],
       [0, 1, 0, 0, 1, 1, 0, 1, 1, 1],
       [0, 0, 0, 1, 1, 1, 1, 0, 0, 1],
       [0, 0, 1, 1, 1, 0, 1, 1, 0, 0],
       [1, 0, 0, 0, 0, 0, 1, 0, 0, 0],
       [1, 0, 1, 0, 1, 0, 0, 0, 0, 1],
       [0, 1, 1, 1, 1, 1, 1, 0, 1, 0]])

In [3]:

targets = np.array([
    [0,3],
    [1,7],
    [2,2],
    [3,5],
    [8,2]
])

In [6]:
rows, cols = targets.T

hints = np.take(sea, rows*10+cols)
hints.T@hints

1

## Boolean indexing

Anytime you have a boolean array, you can use it to mask entries in another array.

In [55]:
a = np.random.randint(0, 100, size=(5,5))
a

array([[90, 33, 21, 71, 68],
       [81, 52, 64, 85, 41],
       [ 1, 14,  3, 30, 12],
       [73, 19, 26, 96, 68],
       [64, 22, 56, 84,  8]])

In [56]:
mask = a > 80
mask

array([[ True, False, False, False, False],
       [ True, False, False,  True, False],
       [False, False, False, False, False],
       [False, False, False,  True, False],
       [False, False, False,  True, False]])

In [57]:
a[mask]

array([90, 81, 85, 96, 84])

Boolean masking may be applied not only to values, but to rows and columns as well. Just remember to use slicing:

*array*[*row_mask*,*col_mask*]

In [58]:
rows_2_and_4 = np.array([False, True, False, True, False])
cols_1_and_2 = np.array([True, True, False, False, False])

In [59]:
a[rows_2_and_4]

array([[81, 52, 64, 85, 41],
       [73, 19, 26, 96, 68]])

In [60]:
a[rows_2_and_4, cols_1_and_2]

array([81, 19])

In [61]:
names = np.array(["Dennis", "Dee", "Charlie", "Mac", "Frank"])
ages = np.array([43, 44, 43, 42, 74])
genders = np.array(['male', 'female', 'male', 'male', 'male'])

In [62]:
names[(genders == 'male') & (ages > 43)]

array(['Frank'], dtype='<U7')

In [63]:
names[~(genders == 'male') & (ages % 2 == 0)]

array(['Dee'], dtype='<U7')

## `Random` module

One of the most frequently used parts of the `NumPy` is the random number generation procedure. Below you can see examples of different samples:
- normal sample
- uniform sample
- choosing from a set with/without replacement

In [64]:
np.random.normal(loc=10.0, scale=1.0, size=10)

array([10.13096188, 10.2627855 , 11.02376449,  9.93740495,  8.81769971,
        9.65524926,  9.75450933,  8.97400477, 10.05442481,  9.59315142])

In [65]:
np.random.randint(low=10, high=20, size=(3,3))

array([[11, 19, 12],
       [17, 14, 13],
       [12, 15, 15]])

In [66]:
np.random.uniform(low=0, high=1, size=5)

array([0.04653158, 0.91735447, 0.15893009, 0.94338268, 0.76316153])

In [69]:
np.random.choice(
    a=[1,2,3,4,5,6],
    replace=True,
    size=5
)

array([5, 5, 6, 5, 2])

In [70]:
np.random.choice(
    a=['this','is','sampling','without','replacement'],
    replace=False,
    size=3
)

array(['this', 'replacement', 'is'], dtype='<U11')

Despite the fact that most people use the `random` module as above, this way is in fact deprecated, because it introduces a dependency on the random number generator used currently by `NumPy`. In theory, if `NumPy` changes the generator, all the code becomes non-reproducible.
A simple solution is to use the generic `Generator` class.

In [71]:
generator = np.random.default_rng(seed=123)

In [72]:
generator.integers(low=1, high=100, size=10)

array([ 2, 68, 59,  6, 90, 22, 26, 19, 34, 18])

In [73]:
generator.normal(loc=0, scale=1, size=10)

array([ 0.57710379, -0.63646365,  0.54195222, -0.31659545, -0.32238912,
        0.09716732, -1.52593041,  1.1921661 , -0.67108968,  1.00026942])

In [74]:
generator.choice(a=[1,2,3], replace=True, size=10)

array([1, 2, 2, 3, 3, 1, 3, 3, 1, 2])

## Homework

### Two reviewers

You are given two arrays representing ratings assigned to 100 movies by two reviewers. Identify movies such that the reviewers differ in their rating by at most 1.

In [75]:
movies = np.arange(100)
reviewer_a = np.random.choice(a=[1,2,3,4,5], size=100)
reviewer_b = np.random.choice(a=[1,2,3,4,5], size=100)

In [87]:
movies_with_similar_review = np.absolute(reviewer_a - reviewer_b) <=1

movies_with_similar_review

array([False,  True,  True, False,  True, False,  True,  True,  True,
       False, False, False, False,  True, False,  True,  True,  True,
       False,  True,  True,  True, False, False, False, False, False,
        True, False,  True,  True,  True, False,  True, False, False,
        True,  True,  True, False, False, False, False, False, False,
        True,  True,  True,  True,  True,  True, False, False,  True,
       False, False, False,  True,  True,  True,  True, False,  True,
        True, False, False, False, False,  True,  True,  True,  True,
       False,  True, False, False,  True,  True,  True,  True,  True,
       False,  True,  True, False,  True,  True, False, False, False,
        True, False,  True,  True, False,  True, False, False,  True,
       False])

## Using `where`

`np.where` is a very useful function which allows to quickly filter elements of an array based on the condition. Imagine you have two large arrays and you want to create a third array such that it contains, for each cell, the larger value from the two arrays. First, let's do it in a traditional way.

In [88]:
a = np.random.randint(1, 6, size=10**5)
b = np.random.randint(1, 6, size=10**5)

In [89]:
%%time
c = np.zeros(a.size)

for i in range(a.size):
    if a[i] > b[i]:
        c[i] = a[i]
    else:
        c[i] = b[i]


CPU times: user 120 ms, sys: 3.04 ms, total: 123 ms
Wall time: 124 ms


In [90]:
%%time
d = np.where(a > b, a, b)

CPU times: user 3.85 ms, sys: 101 µs, total: 3.96 ms
Wall time: 2.3 ms


In [91]:
np.array_equal(c,d)

True

## Homework

### First to finish the assignment

Given an array with students' assignments ordered by the increasing date of submission, you want to reward first 3 students who submitted their work and who got at least 75 points. Increase their scores by 5 points.

In [5]:
grades = np.random.randint(low=0, high=100, size=50)
ind = np.where(grades > 75)[0][:3]
grades[ind]+=5

## Math functions

`NumPy` contains several highly optimized implementations of math functions. Whenever possible, try to use them instead of your own implementations. Remember, that math functions are easily generalized to n-dim arrays.

In [105]:
a = np.array([
    [1, 2, 3, 4],
    [5, 6, 7, 8],
    [9, 10, 11, 12],
    [13, 14, 15, 16],
], dtype=np.float64)

In [106]:
np.sum(a)

136.0

In [107]:
np.sum(a, axis=0)

array([28., 32., 36., 40.])

In [108]:
np.sum(a, axis=1)

array([10., 26., 42., 58.])

But beware of `nan`s, as they tend to destroy all math!

In [109]:
a[2,2] = np.nan

In [110]:
np.sum(a)

nan

In [111]:
np.isnan(a)

array([[False, False, False, False],
       [False, False, False, False],
       [False, False,  True, False],
       [False, False, False, False]])

In [112]:
np.sum(a, where=~np.isnan(a))

125.0

In [113]:
np.nansum(a)

125.0

In [116]:
np.sum(np.nan_to_num(a))

125.0

Let's see what else we can do with `nan`s

In [117]:
a[0,1] = np.nan
a[1,3] = np.nan

In [118]:
np.isnan(a)

array([[False,  True, False, False],
       [False, False, False,  True],
       [False, False,  True, False],
       [False, False, False, False]])

In [119]:
np.any(np.isnan(a), axis=1)

array([ True,  True,  True, False])

In [120]:
mask = np.any(np.isnan(a), axis=1)
a[mask]

array([[ 1., nan,  3.,  4.],
       [ 5.,  6.,  7., nan],
       [ 9., 10., nan, 12.]])

## Concatenation & sorting

Concatenation means joining two arrays by rows or by columns. An array may be concatenated with itself or with another array. There are 4 functions that help with concatenation.

In [123]:
a = np.zeros(shape=(3,2))
b = np.ones(shape=(2,2))

In [124]:
np.concatenate([a, a, a, a], axis=0)

array([[0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.]])

In [125]:
np.concatenate([a, b], axis=0)

array([[0., 0.],
       [0., 0.],
       [0., 0.],
       [1., 1.],
       [1., 1.]])

In [126]:
np.vstack([a,b])

array([[0., 0.],
       [0., 0.],
       [0., 0.],
       [1., 1.],
       [1., 1.]])

In [127]:
np.hstack([a.T,b])

array([[0., 0., 0., 1., 1.],
       [0., 0., 0., 1., 1.]])

In [128]:
np.stack([a[:2,:2], b], axis=0)

array([[[0., 0.],
        [0., 0.]],

       [[1., 1.],
        [1., 1.]]])

Unfortunately, `NumPy` does not provide any easy way of reverse sort, and sorting is limited to two functions.

In [129]:
a = np.random.randint(1, 100, size=50)
a

array([45, 35, 19,  5, 76, 74, 74, 60, 78, 99,  8,  6, 72, 54, 17, 81, 59,
       32, 30, 70, 16, 49, 34, 65, 63, 87, 84, 98, 96, 14, 48, 61, 98, 99,
       45, 15, 55, 51, 68, 78, 56, 60, 99, 38, 52, 86, 63, 20, 60, 29])

In [130]:
a.sort()

In [131]:
a

array([ 5,  6,  8, 14, 15, 16, 17, 19, 20, 29, 30, 32, 34, 35, 38, 45, 45,
       48, 49, 51, 52, 54, 55, 56, 59, 60, 60, 60, 61, 63, 63, 65, 68, 70,
       72, 74, 74, 76, 78, 78, 81, 84, 86, 87, 96, 98, 98, 99, 99, 99])

In [132]:
np.sort(a)[::-1]

array([99, 99, 99, 98, 98, 96, 87, 86, 84, 81, 78, 78, 76, 74, 74, 72, 70,
       68, 65, 63, 63, 61, 60, 60, 60, 59, 56, 55, 54, 52, 51, 49, 48, 45,
       45, 38, 35, 34, 32, 30, 29, 20, 19, 17, 16, 15, 14,  8,  6,  5])

If you want to be able to sort values in the first column of an array according to the order in the second column of an array, you need to use `np.argsort`.

In [133]:
a = np.random.randint(1, 100, size=20)
a.shape = 5,4

a

array([[68,  4,  5, 73],
       [23, 51, 13, 16],
       [29, 17, 63, 48],
       [72,  1, 75, 13],
       [92, 50, 69, 27]])

In [134]:
np.sort(a, axis=1)

array([[ 4,  5, 68, 73],
       [13, 16, 23, 51],
       [17, 29, 48, 63],
       [ 1, 13, 72, 75],
       [27, 50, 69, 92]])

In [137]:
a

array([[68,  4,  5, 73],
       [23, 51, 13, 16],
       [29, 17, 63, 48],
       [72,  1, 75, 13],
       [92, 50, 69, 27]])

In [138]:
a[np.argsort(a[:,1])]

array([[72,  1, 75, 13],
       [68,  4,  5, 73],
       [29, 17, 63, 48],
       [92, 50, 69, 27],
       [23, 51, 13, 16]])